mysql-user : bitcointip
mysql-pass : randompass1234
mysql-host : localhost
mysql-port : 3306
mysql-db: bitcointip

bitcoind-rpclogin : bitcoinrpc
bitcoind-rpcpass : randompass1234
bitcoind-rpchost : localhost
bitcoind-rpcport : 8332
bitcoind-walletpass : verysecurepass1234

reddit-username : mybitcointipuser
reddit-pass : randompass1234
reddit-useragent : mybitcointipuser
reddit-botsubreddit : mybitcointipsubreddit
reddit-watchsubreddits : [ 'subreddit1', 'subreddit2' ]

admin-email : admin@example.com
